### ISSUE TITLE
RasterFormatException when using IE

### ISSUE THREAD

**Issue by miteshpatel1** [vinsguru/ocular#1]
Hello,

Just started using this library last week and have run into a slight problem with Internet explore. Before it can take the snapshot, it throws the following error:

Started InternetExplorerDriver server (32-bit)
3.6.0.0
Listening on port 23841
Only local connections are allowed
Oct 02, 2017 7:44:59 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

`Scenario: Item can be added to shopping cart # C:/Users/mitesh.patel/Documents/repo/src/test/resources/features/add_item_to_shopping_cart.feature:11
    Given I have searched for 'cotton'         # ShoppingCartStepDefs.givenIHaveSearchedFor(String)
      java.awt.image.RasterFormatException: (x + width) is outside of Raster
        at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1245)
        at java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
        at com.testautomationguru.ocular.comparator.ImageUtil.getElementSnapshot(ImageUtil.java:42)
        at com.testautomationguru.ocular.sample.SampleBuilderImpl.element(SampleBuilderImpl.java:46)
        at example.ui.pages.HomePage.comparePage(HomePage.java:34)
        at example.ui.steplibs.CustomerSteps.checkHomepageLookAndFeel(CustomerSteps.java:24)
        at example.ui.steplibs.CustomerSteps$$EnhancerByCGLIB$$b1957b7d.CGLIB$checkHomepageLookAndFeel$6(<generated>)
        at example.ui.steplibs.CustomerSteps$$EnhancerByCGLIB$$b1957b7d$$FastClassByCGLIB$$948f9cde.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:395)
        at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:380)
        at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:355)
        at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:132)
        at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
        at example.ui.steplibs.CustomerSteps$$EnhancerByCGLIB$$b1957b7d.checkHomepageLookAndFeel(<generated>)
        at example.ui.stepdefs.ShoppingCartStepDefs.givenIHaveSearchedFor(ShoppingCartStepDefs.java:37)`

I don;t see this issue with Chrome. Any thoughts what could be causing it?

**Comment by miteshpatel1** [comment]
Apologies - this was due to a mismatch in driver and selenium versions!
