### ISSUE TITLE
Getting null pointer exception

### ISSUE THREAD

**Issue by sunnysachdeva** [vinsguru/ocular#6]
My Page class

```
public class WynPageClass {

	private WebDriver driver;
	private Map<String, String> map;
	
	@FindBy(xpath="//img[@alt='Anita Baker & Jardin Dinner Pairing']")
	private WebElement element;
	
	public WynPageClass(WebDriver driver){
		this.driver=driver;
		map = new HashMap<String, String>();
		map.put("snap1", "snap1.jpg");
	}
	
	
	public boolean match(){
		return this.verifyChart(map.get("snap1"), element);
	}
	
	private boolean verifyChart(String fileName, WebElement element) {
        Path path = Paths.get(fileName);
        OcularResult result = Ocular.snapshot()
                                    .from(path)
                                    .sample()
                                    .using(driver)
                                    .element(element)
                                    .compare();

        return result.isEqualsImages();
    }
}
```
TestNG based test class

```
public class OcularVisual {

	public WebDriver driver;
	private WynPageClass page;

	@BeforeSuite
	public void bs(){
		System.setProperty("webdriver.chrome.driver", "E:\\Softwares\\chromedriver.exe");
		driver = new ChromeDriver();
		Ocular.config()
		.snapshotPath(Paths.get("E:\\workspace\\NewTech\\src\\test\\resources/snap"))
		.resultPath(Paths.get("E:\\workspace\\NewTech\\src\\test\\resources\\result"));

	}
	
	

	@Test
	public void testA(){
		driver.get("https://intg.wynntesting.com/dining");
		page = new WynPageClass(driver);
		Assert.assertTrue(page.match());
	}


	@AfterSuite
	public void as(){
		driver.quit();
	}

	public boolean verifyImage(String fileName, WebElement element){
		Path path = Paths.get(fileName);
		OcularResult result = Ocular.snapshot()
				.from(path)
				.sample()
				.using(driver)
				.element(element)
				.compare();

		return result.isEqualsImages();
	}
```

Exception
java.lang.NullPointerException
	at com.testautomationguru.ocular.comparator.ImageUtil.getElementSnapshot(ImageUtil.java:39)
	at com.testautomationguru.ocular.sample.SampleBuilderImpl.element(SampleBuilderImpl.java:46)

@vinsguru Can you pls help

**Comment by uselvvi** [comment]
@sunnysachdeva 

Looks like the WebElement is null. You need to check your locator!

**Comment by vinsguru** [comment]
@sunnysachdeva  is this still an issue?

**Comment by vinsguru** [comment]
Closing this as no updates from the user
